### ISSUE TITLE
install.packages("ReSources") issues

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/drat#4]
# Download **ReSources** package in R
Run these codes in your local R console:

- `options(repos = c(getOption("repos"), PANDORA = "https://Pandora-IsoMemo.github.io/drat/"))`
- `install.packages("ReSources")`

## How to start the app:
- `library(ReSources)`
- `ReSources::startApplication()`

# HOW TO REPORT BUGS:

If you have issues installing the packages, please report your issue here with the package name and what steps you have already done, preferably as descriptive as possible (screenshots, etc.). We will get back to you as soon as we can to solve the issue.

## Can please provide:

> - All commands that led to the installation error: 
> - The full output of `sessionInfo()`
> - The output of `options("repos")`

**Comment by jroachell15** [comment]
@isomemo 

Dear Ricardo, you can comment here in the future if you have more installation issues: Pandora-Isomemo > DRAT >  ISSUES > pick the packages name thread that pertains to you. 

The instructions to install all IsoMemo packages are here: https://github.com/Pandora-IsoMemo/drat

Please report in this thread any installation bugs as you see. Thanks!

**Comment by jroachell15** [comment]
Hi Carlo,

yes, that's correct. after you run this command in R: `options(repos = c(getOption("repos"), PANDORA = "https://pandora-isomemo.github.io/drat/")) `, nothing should happen, which means it's connected. 

next, you should run "install.packages("ReSources")

did it work for you? if not, please provide the template for HOW TO REPORT AN BUG/ISSUE as seen above. thanks!

**Comment by CarloCocozza** [comment]
Hi Jian,

I installed the ReSources package and I have it within my library now. But how do I have access to the interface?

**Comment by CarloCocozza** [comment]
> 

Forgot to tag @jroachell15

**Comment by jroachell15** [comment]
@CarloCocozza Please refer to the (newly-added) directions on the top of this thread to start the user interface of ReSources. thanks! let me know if you have anymore questions! :)

**Comment by CarloCocozza** [comment]
Hi @jroachell15 , Thanks for your patience but I think I would need some little more of it. I am very confused because I never used R before and I know basically nothing about coding. Let's do the following, I'll tell you the steps I am following and let's see where I am mistaken:
1) I open R (or should I open R:Studio?)
2) I copy paste 

options(repos = c(getOption("repos"), PANDORA = "https://pandora-isomemo.github.io/drat/"))

 and it doesn't do anything which means it is connected.
3) I copy paste 

install.packages("ReSources") 

and then it asks me for a Mirror. I choose one from Italy
4) I eventually get this:

 The downloaded source packages are in
        ‘C:\Users\Utente\AppData\Local\Temp\RtmpegBqu9\downloaded_packages’

 but actually I cannot find this folder
5) Anyway I go to load packages and I click on ReSources (which is there, meaning it is installed I suppose)
6) the console says something about loading nimble and then I get a message (in italian) that translated means something like 

"The following object is masked by ‘package:stats’ : 
simulate"

7) Now do I need to copy paste

install.packages("devtools")
library(devtools)
install.packages("ReSources") 

? Or should I have done that at the beginning?

8) If I copy paste 

devtools::load_all('.')

I receive:

Error:
! Could not find a root 'DESCRIPTION' file that starts with '^Package' in 'C:\Users\Utente\Documents'. Are you in your project directory, and does your project have a 'DESCRIPTION' file?
Run `rlang::last_error()` to see where the error occurred.


I apologise again for the confusion. 
Perhaps could you mention all the R prerequisites to run the model? I have the suspect that I need to install some other software too.

**Comment by jroachell15** [comment]
@CarloCocozza
no Problem. It's totally fine. 

Let's start over by uninstalling ReSources pacakge: `remove.packages("ReSources")`

Then start from the [prerequisite](https://github.com/Pandora-IsoMemo/drat/issues/4#issue-1164941192) until you have successfully initiated `startApplication()`

let me know if you prefer we jump on a call.

**Comment by CarloCocozza** [comment]
@jroachell15 I think I did it! 
But is the local interface still opened in the browser? I thought it was opened in R. Another question, do I need to follow the same process to install also isomemo?

Thanks a lot!

**Comment by jroachell15** [comment]
@CarloCocozza Just to solve one of the issues we had on the call: Running apps consecutively, but the previous app appeared instead. We ran `ReSources App` then installed `MpiIsoApp`, but the ReSources interface appeared instead when we ran `startApplication()`. 
**Solution**:
when starting a new application in the console, specify the package name in this format: `{package}::startApplication()`. 
In our case, we need to use `ReSources::startApplication()` and `MpiIsoApp::startApplication()` to initiate the relevant apps. I hope that helps?

**Comment by CarloCocozza** [comment]
@jroachell15 This doesn't seem to work for IsoMemo. When I use the code, I get a page on the Browser that says: 

An error has occurred!
lexical error: invalid char in json text. dbsources? (right here) ------^

**Comment by jroachell15** [comment]
@CarloCocozza 

yes, I see. Could you please try it with the other apps like:
`PlotR::startApplication()`

**Comment by CarloCocozza** [comment]
@jroachell15 This one seems to work!

**Comment by jan-abel-inwt** [comment]
see https://github.com/Pandora-IsoMemo/resources/issues/68

content can now be found here: https://github.com/Pandora-IsoMemo/resources/wiki
